### ISSUE TITLE
Why is Mellanox PeerDirect disabled?

### ISSUE THREAD

**Issue by ksm9413** [developer-onizuka/gpudirect_storage_1.0#3]
An error occurred while building GDS in a distributed file system environment, so I found out that PeerMemory is disabled.

<cat /proc/driver/nvidia-fs/stats>
GDS Version: 1.1.1.20 
NVFS statistics(ver: 4.0)
NVFS Driver(version: 2.9.5)
Mellanox PeerDirect Supported: False
IO stats: Disabled, peer IO stats: Enabled

ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

<gdscheck>
 NVMe               : Supported

 NVMeOF             : Unsupported

 SCSI               : Unsupported

 ScaleFlux CSD      : Unsupported

 NVMesh             : Unsupported

 DDN EXAScaler      : Unsupported

 IBM Spectrum Scale : Unsupported

 NFS                : Unsupported

 BeeGFS             : Unsupported

 WekaFS             : Unsupported

 Userspace RDMA     : Unsupported

 --Mellanox PeerDirect : Disabled

 --rdma library        : Not Loaded (libcufile_rdma.so)

 --rdma devices        : Not configured

 --rdma_device_status  : Up: 0 Down: 0

GDS version 1.1 is used, OS centos 8.4, kernel 4.18.0-305.3.1.el8_4.x86_64 is in use. I installed mofed version 5.4 before installing GDS.

**Comment by developer-onizuka** [comment]
According to the URL below, kernel 4.18 might not be supported for GDS.
https://docs.nvidia.com/gpudirect-storage/release-notes/index.html#mofed-fs-req

As you might understand, PeerDirect is important to do DMA between PCI devices. The DMA about GDS is performed by the DMA engine of NVMe device. But, NVMe Driver itself can not let the NVMe's DMA Engine know the GPU's BAR which is target address of DMA. The kernel plays important roles for that. 
See also the URL below:
https://github.com/developer-onizuka/what_is_GPUDirect-Storage#4-how-to-know-the-bar-space-
