### ISSUE TITLE
Question about unsupported NVMe

### ISSUE THREAD

**Issue by rthenamvar** [developer-onizuka/gpudirect_storage_1.0#4]
Hope everything is great for you. I'm trying to do a student project on GDS and want to use a NVMe storage but haven't connected the NVMe to the computer yet (I haven't bought it yet). I installed all the packages. When I run the `gdscheck.py` program, I get this result which says the NVMe is unsupported:
```
 ============
 ENVIRONMENT:
 ============
 =====================
 DRIVER CONFIGURATION:
 =====================
 NVMe               : Unsupported
 NVMeOF             : Unsupported
 SCSI               : Unsupported
 ScaleFlux CSD      : Unsupported
 NVMesh             : Unsupported
 DDN EXAScaler      : Unsupported
 IBM Spectrum Scale : Unsupported
 NFS                : Unsupported
 BeeGFS             : Unsupported
 WekaFS             : Unsupported
 Userspace RDMA     : Unsupported
 --Mellanox PeerDirect : Disabled
 --rdma library        : Not Loaded (libcufile_rdma.so)
 --rdma devices        : Not configured
 --rdma_device_status  : Up: 0 Down: 0
 =====================
 CUFILE CONFIGURATION:
 =====================
 properties.use_compat_mode : true
 properties.gds_rdma_write_support : true
 properties.use_poll_mode : false
 properties.poll_mode_max_size_kb : 4
 properties.max_batch_io_size : 128
 properties.max_batch_io_timeout_msecs : 5
 properties.max_direct_io_size_kb : 16384
 properties.max_device_cache_size_kb : 131072
 properties.max_device_pinned_mem_size_kb : 33554432
 properties.posix_pool_slab_size_kb : 4 1024 16384 
 properties.posix_pool_slab_count : 128 64 32 
 properties.rdma_peer_affinity_policy : RoundRobin
 properties.rdma_dynamic_routing : 0
 fs.generic.posix_unaligned_writes : false
 fs.lustre.posix_gds_min_kb: 0
 fs.beegfs.posix_gds_min_kb: 0
 fs.weka.rdma_write_support: false
 profile.nvtx : false
 profile.cufile_stats : 0
 miscellaneous.api_check_aggressive : false
 =========
 GPU INFO:
 =========
 GPU index 0 NVIDIA GeForce RTX 3060 bar:1 bar size (MiB):256
 ==============
 PLATFORM INFO:
 ==============
 IOMMU: disabled
 Platform verification succeeded
```
Is it because I haven't connected the NVMe to my PC yet?
Thanks

**Comment by developer-onizuka** [comment]
>Is it because I haven't connected the NVMe to my PC yet?

I believe that DMA between GPU and NVMe is done thru the copy between GPU BAR space and NVMe Bar space by "NVMe's DMA Engine". I think that the NVMe's DMA Engine plays an important role of it. So, If you don't install NVMe then it might be one of the reasons of it.

> GPU index 0 NVIDIA GeForce RTX 3060 bar:1 bar size (MiB):256

But, I found your GPU might NOT be suitable for GPUDirect Storage.
According to the Nvidia's github below, "NVIDIA Tesla or Quadro class GPUs based on Pascal, Volta, Turing or Ampere".
https://github.com/NVIDIA/gds-nvidia-fs/blob/master/README.md

I believe that RTX3060 is GeForce device. This might be also a kind of reasons that the NVMe is unsupported.

Best,

**Comment by rthenamvar** [comment]
so many thanks for your guidance. I read somewhere in Nvidia documentation that RTX3060 is supported only in compatibility mode.
Besides, my Linux kernel is 5.13.x. May it be the cause of the problem?

**Comment by developer-onizuka** [comment]
Hi,

>https://docs.nvidia.com/gpudirect-storage/release-notes/index.html#mofed-fs-req

The release note says 5.4.x is supported. The kernel version is important because Existing operating systems attempting to program DMA engines cannot process GPU virtual addresses without help. These kernels supported might have some modification. See also below: But your kernel version might gets well recently.

>https://github.com/developer-onizuka/what_is_GPUDirect-Storage#4-how-to-know-the-bar-space-

Good luck.

**Comment by rthenamvar** [comment]
I really appreciate your help. Yeah I had read it, but since the system I’m using is shared between me and other students, couldn’t uninstall the OS and reinstall everything from scratch. Is it possible to downgrade the kernel without reinstalling the OS, Cuda and MLNX_OFED?

**Comment by developer-onizuka** [comment]
Hi,

```
$ sudo apt-get install linux-image-5.4.0-42-generic linux-headers-5.4.0-42-generic linux-modules-extra-5.4.0-42-generic
$ sudo vi /etc/default/grub
  You should edit as followings, please note the GRUB_TIMEOUT_STYLE and GRUB_TIMEOUT parameters are comment out:
#GRUB_TIMEOUT_STYLE=hidden
GRUB_TIMEOUT=-1
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash intel_iommu=off"

$ sudo update-grub
$ reboot
```
After this step, You will be able to select kernel 5.4.0-42. This is No needs to OS reinstall.


You might also use virtual machine and GDS on it.
See also below:

> https://github.com/developer-onizuka/gpudirect_storage_1.1_VirtualMachine

**Comment by rthenamvar** [comment]
so many thanks, so I won’t need to reinstall Cuda, MLNX_OFED and GDS to make drivers and ... work correctly right?

**Comment by developer-onizuka** [comment]
Hi,

You may unfortunately need to reinstall OFED at least because I believe you added some options such as --add-kernel-support which adequate for the kernel you boot while installing OFED as like below:

> mlnxofedinstall --with-nfsrdma --with-nvmf --enable-gds --add-kernel-support

**Comment by rthenamvar** [comment]
so many thanks for your guidance. I wish I had found you sooner :))
u helped me a lot

**Comment by developer-onizuka** [comment]
Feel free if you have any problems.
